### ISSUE TITLE
FYI: shift F1 got broken

### ISSUE THREAD

**Issue by megabugman** [maestrith/AHK-Studio#109]
[![quicks21.gif](https://s14.postimg.org/cad40hgkx/quicks21.gif)](https://postimg.org/image/44v22bsbx/)

going to sleep now. good night or day! :)

**Comment by maestrith** [comment]
yep :) I was working on that when you added other things :)

**Comment by maestrith** [comment]
Good Night

**Comment by maestrith** [comment]
Should be fixed

**Comment by megabugman** [comment]
> Should be fixed

there is still an issue
[![quicks24.gif](https://s11.postimg.org/s1l29hcgj/quicks24.gif)](https://postimg.org/image/3xual6tzj/)

**Comment by maestrith** [comment]
I can not get this to re-produce.  Please let me know if this is still an issue

**Comment by megabugman** [comment]
closed
