### ISSUE TITLE
AHK-Studio not always showing file in it's true state

### ISSUE THREAD

**Issue by evilC** [maestrith/AHK-Studio#77]
I had a number of instances last night where Studio was showing the file as being in one state, but my GitHub client was showing it in a different state.  
In all cases, there was a line in the file which I had deleted in Studio and hit Save, but the save was not written to disk and Studio was erroneously showing the file without the line.  
Closing Studio and re-opening showed the line again.  
I *think* this is related to debugging. If memory serves correctly, it was generally happening on the line after a breakpoint.

**Comment by maestrith** [comment]
Please let me know when you can repro and not _think_ but know.

**Comment by TWF1212** [comment]
I believe I am having the same issue as described here. However for me it is very consistent, deleting does not flag a file as updated for me. Saving (Ctrl-S) doesn't save the deletion, and the only way to get AHK Studio to show the deleted text again is to restart it.

I noticed the issue when I went to make the Run (Alt-E) command fail on purpose, but then deleted the offensive text and re-ran and got the same error claiming specifically the just deleted text.

I am using version 1.003.13, I've only tweaked theme settings, and added 'this' to the builtins.

**Comment by kwoodhouse** [comment]
AHK Studio V 1.003.16
AutoHotKey V 1.1.24.05
Windows 10 Pro V1607, Buil 14393.953

Here is a consistent reproduction.  Run by Alt-R
![image](https://cloud.githubusercontent.com/assets/6086755/24404633/3ed473c4-1390-11e7-9d49-c87301bae99a.png)

Backspaced to correct and reran by Alt-R
![image](https://cloud.githubusercontent.com/assets/6086755/24404593/23cce930-1390-11e7-868c-18ecc7113cbd.png)

**Comment by nnnik** [comment]
I think this has been fixed in the latest Version.

**Comment by kwoodhouse** [comment]
Much better in 1.003.17, but still occasionally still experiencing the issue.  Can't yet narrow it down to a repeatable scenario.
